"""got rid of tag in Projects to setup n to n connection

Revision ID: 1fce5180acc2
Revises: 866eda39d2c2
Create Date: 2026-03-31 00:20:14.207282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fce5180acc2'
down_revision = '866eda39d2c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
