"""made picture URL nullable

Revision ID: 866eda39d2c2
Revises: afa9254be24a
Create Date: 2026-03-31 00:08:46.379705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866eda39d2c2'
down_revision = 'afa9254be24a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('picture_url',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('picture_url',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
